export type AlignEdge =
  | 'left'
  | 'center'
  | 'right'
  | 'top'
  | 'middle'
  | 'bottom'
  | 'left top'
  | 'left middle'
  | 'left bottom'
  | 'center top'
  | 'center middle'
  | 'center bottom'
  | 'right top'
  | 'right middle'
  | 'right bottom'
  | 'top left'
  | 'middle left'
  | 'bottom left'
  | 'top center'
  | 'middle center'
  | 'bottom center'
  | 'top right'
  | 'middle right'
  | 'bottom right';
